name: Push actions

on:
  push:
    branches:
      - main
      - dev

jobs:
  tests:
    runs-on: "ubuntu-latest"
    name: Run tests
    steps:
      - name: Check out code from GitHub
        uses: "actions/checkout@v2"
      - name: Setup Python
        uses: "actions/setup-python@v1"
        with:
          python-version: "3.8"
      - name: Install requirements
        run: python3 -m pip install -r requirements_test.txt -r requirements_release.txt
      - name: Run tests
        run: |
          python3 -m pytest tests
